name: API Integration Tests

on:
  push:
    branches: [ feat/newman-api-test-pipeline ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    env:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Start Services
        run: docker compose -f docker-compose.test.yml up -d --build
      
      - name: Check Early Logs
        run: |
          sleep 10
          docker compose -f docker-compose.test.yml logs api

      - name: Wait for API (Seeding + Boot)
        run: npx wait-on -v http-get://127.0.0.1:3000/health --timeout 90000

      - name: Run Newman Tests
        run: |
          npm install -g newman-reporter-htmlextra
          mkdir -p newman

          npx newman run ./tests/collection.json \
          -e ./tests/environment.template.json \
          --env-var "base_url=http://localhost:3000" \
          --env-var "test_username=${{ secrets.TEST_USERNAME }}" \
          --env-var "test_password=${{ secrets.TEST_PASSWORD }}"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: ./newman/report.html

      - name: Stop Services
        if: always()
        run: docker compose -f docker-compose.test.yml down